[package]
name                   = "glypher-cli"
version                = "0.1.0"
authors.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "Command line interface for glypher, converts images to ascii art"
documentation          = "https://docs.rs/glypher-cli"
readme                 = "README.md"
homepage.workspace     = true
repository.workspace   = true
license.workspace      = true
keywords               = ["ascii", "ascii-art", "cli", "image", "logo"]
categories             = ["command-line-utilities", "multimedia::images"]
include                = ["LICENSE", "README.md", "src/**/*.rs"]

[[bin]]
name = "glypher"
path = "src/main.rs"

[dependencies]
clap.workspace      = true
glypher.workspace   = true
thiserror.workspace = true
ureq.workspace      = true
